language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - nightly
    - hhvm

env:
 - SYMFONY_VERSION=2.8.*
 - SYMFONY_VERSION=3.0.*
 - SYMFONY_VERSION=3.1.*
 - SYMFONY_VERSION=3.2.*
 - SYMFONY_VERSION=3.3.*

branches:
    only:
        - master
        - /^\d+\.\d+$/

#symfony 3.0 is no longer supported by symfony, allow it to fail
matrix:
    allow_failures:
        - php: nightly
        - php: hhvm
        - env: SYMFONY_VERSION=3.0.*

before_script:
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer self-update
    - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
    - composer update --prefer-dist

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# Run coveralls ONLY if under php native, and NOT hhvm
after_success: |
 sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "hhvm-nightly" ]; then php vendor/bin/coveralls -v --config .coveralls.yml; fi;'

notifications:
    email: julienguyon@hotmail.com
